# -*- coding: utf-8 -*-
"""PuTTY_config.ipynb

Automatically generated by Colaboratory.

login as: admin
admin@192.168.1.1's password:


BusyBox v1.30.1 () built-in shell (ash)

 -----------------------------------------------------------------
  _____ _   _ _______ ______ _      ____  _____             _____
 |_   _| \ | |__   __|  ____| |    |  _ \|  __ \     /\    / ____|
   | | |  \| |  | |  | |__  | |    | |_) | |__) |   /  \  | (___
   | | | . ` |  | |  |  __| | |    |  _ <|  _  /   / /\ \  \___ \
  _| |_| |\  |  | |  | |____| |____| |_) | | \ \  / ____ \ ____) |
 |_____|_| \_|  |_|  |______|______|____/|_|  \_\/_/    \_\_____/

 ------------------------------------------------------------------

admin@GX 3000:~# ?
-ash: ?: not found
admin@GX 3000:~# ls
admin@GX 3000:~# cd ..
admin@GX 3000:/# ls
bin      dev      init     overlay  root     tmp      vendor
cfg      etc      lib      proc     sbin     usr      webapps
data     ini      mnt      rom      sys      var      www
admin@GX 3000:/# cd lib/
admin@GX 3000:/lib# ls
compress_vart.sh          libgcc_s.so.1             preinit
config                    libjson_script.so         read_caldata_to_fs.sh
debug                     libprovision.so           sbin
easymesh.sh               librpc.so                 sound
filter                    libsetlbf.so              speedtest
firmware                  libssp.so.0               tr069_firewall
functions                 libssp.so.0.0.0           uboot-envtools.sh
functions.sh              libubox.so                uci
hw_def.sh                 libubus.so                update_smp_affinity.sh
ipq806x.sh                libuci.so                 update_system_params.sh
ld-musl-arm.so.1          libvalidate.so            upgrade
ledd                      modem_readd               wifi
libblobmsg_json.so        modules                   wifi_interface_helper.sh
libc.so                   netifd
libfstools.so             network
admin@GX 3000:/lib#
